
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from './components/Navbar'
import { ToastContainer } from "react-toastify";
import Provider from "./Provider";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Cre8-ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
    <ClerkProvider>
    <html lang="en">
    <head>
        
          <link rel="icon" href="/robot.png" type="image/png" />
        </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div data-theme="sunset" className="bg-[#0202029d]">
        {/* <Navbar/> */}
        <Provider>
        {children}
        </Provider>
        <ToastContainer/>
        </div>
      </body>
    </html>
    </ClerkProvider>
   
  );
}
// bg-[#0202029d]